## Ex5A NumPy Fundamentals Lab 1
### Working with NumPy

In [2]:
import numpy as np

## Array Basics

In [3]:
fruits = ['apple','banana','cherry','date']

In [4]:
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [16]:
print(arr_1.dtype)
# The data type that is returned is U6 which the U is unicorn string and 6 is the max length of the strings in the array

<U6


In [18]:
arr_2 = ([10,11,12],[13,14,15])

In [19]:
arr_2 = np.array(arr_2)
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [22]:
print(arr_2.T) # It does not alter the value stored in arr_2

[[10 13]
 [11 14]
 [12 15]]


In [23]:
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [27]:
arr_3 = ([1,3,5],[2,4,6])
arr_3 = np.array(arr_3)
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [30]:
arr_4 = np.array([arr_3[0,2],arr_3[1,1]])
print(arr_4)

[5 4]


In [32]:
arr_5 = np.ones((2,2,2))
print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
