# Exercise 1.A NumPy: Manipulating Arrays

In [3]:
import numpy as np

## Looping Through Arrays

In [4]:
arrA = np.array([[11,12,13],[14,15,16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [5]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [6]:
for x in arrA:
    for y in x:
        print(y*2)

22
24
26
28
30
32


# Describing the differences between looping through the first dimension and looping through the second
 The difference is that looping through the first dimension output showed what was in the second dimension and formatted as an array
 For the looping through the second dimension the output was that the values were transposed and didn't have any brackets it was just the integers

In [12]:

for x in arrA:
    for y in x:
        loop_result = x * 2
    print(loop_result)



# This result is different because it only mulltiplied index 1 instead of multiplying both indexes

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [16]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [18]:
joined_array_2 = np.concatenate((arrA,arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [23]:
stacked_array_1 = np.stack((joined_array_1,joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [25]:
stacked_array_2 = np.stack((joined_array_1,joined_array_2))
# The error message I get is a valueError all input arrays must have the same shape

ValueError: all input arrays must have the same shape

In [27]:
another_joined_array = np.concatenate((joined_array_1,arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [28]:
another_2 = np.concatenate((joined_array_1,arrA),axis=1)
# The arrays are different sizes and need to match in size in order to concatenate 

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [31]:
arr_hstack = np.hstack((arrA,arrA)) # stacks each 1D arrays horizontally 
arr_vstack = np.vstack((arrA,arrA)) # stacks each 1D arrays on to top of each vertically
arr_dstack = np.dstack((arrA,arrA)) # stacks each 1D arrays in a third dimension for depth

print(arr_hstack) 
print(f'\n{arr_vstack}') 
print(f'\n{arr_dstack}')

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]

[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [36]:
splitsky = np.split(joined_array_1, 2)
print(splitsky) 
# it split it into 2 arrays with 2 dimensions each array

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [37]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)
# it split it into 3 arrays with 2 dimensions each array

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and replacing Array Values

In [50]:
result_1 = np.where(arrA % 2 == 0, 'arrA', 'Odd')
print(result_1)

[['Odd' 'arrA' 'Odd']
 ['arrA' 'Odd' 'arrA']]


## Sorting and Filtering Arrays

In [54]:
arrB = np.array(([[7,6],[13,5],[7,3]]))
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [58]:
print(arrB)

z = arrB < 7
arrC = arrB[z]
print(f'\n{arrC}')

[[ 7  6]
 [13  5]
 [ 7  3]]

[6 5 3]


In [59]:
print(arrB)

y = arrB >= 7
arrD = arrB[y]

print(f'\n{arrD}')

[[ 7  6]
 [13  5]
 [ 7  3]]

[ 7 13  7]
