# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

In [4]:
arrA = np.array([[11,12,13],[14,15,16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [7]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [8]:
for x in arrA:
    for y in x:
        print(y*2)

22
24
26
28
30
32


# Describing the differences between looping through the first dimension and looping through the second
 The difference is that looping through the first dimension output showed what was in the second dimension and formatted as an array
 For the looping through the second dimension the output was that the values were transposed and didn't have any brackets it was just the integers

In [11]:
loop_result = x * 2
for x in arrA:
    for y in x:
        print(x)

print(loop_result)

[11 12 13]
[11 12 13]
[11 12 13]
[14 15 16]
[14 15 16]
[14 15 16]
[28 30 32]


## Joining and Stacking Arrays

In [16]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [18]:
joined_array_2 = np.concatenate((arrA,arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [23]:
stacked_array_1 = np.stack((joined_array_1,joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [25]:
stacked_array_2 = np.stack((joined_array_1,joined_array_2))
# The error message I get is a valueError all input arrays must have the same shape

ValueError: all input arrays must have the same shape

In [27]:
another_joined_array = np.concatenate((joined_array_1,arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [28]:
another_2 = np.concatenate((joined_array_1,arrA),axis=1)
# The arrays are different sizes and need to match in size in order to concatenate in dimension 1?

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2