# Exercise 1.B NumPy Random

In [2]:
import numpy as np


## Generating Random Numbers

In [10]:
# Create a variable named r_1 that contains a random set of integers between 1 and
# 20 with a size of 2 elements. Print r_1.

r_1 = np.random.randint(1,20, size=(2))
print(r_1)

[11 17]


In [ ]:
# Create a variable named r_2 that contains a random set of integers between 1 and
# 20 with a size of 1 row, 2 columns. Print r_2.

r_2 = np.random.randint(1,20,size=(1,2))
print(r_2)

[[8 2]]


In [83]:
# Create a variable named r_3 that contains a random set of floats between 0 and 1
# with a size of 2 rows, 1 columns. Print r_3.

r_3 = np.random.rand(1,20)
print(r_3)

[[0.03782534 0.42616734 0.34512523 0.34313254 0.41089921 0.3870126
  0.065599   0.29514507 0.91498101 0.51880676 0.39625169 0.2994876
  0.19409664 0.75463031 0.4494453  0.92707901 0.18424053 0.29136176
  0.46847786 0.04297034]]


In [84]:
# Create a variable named r_4 that contains a random set of integers between 20
# and 100 with a size of 4 rows, 5 columns. Print r_4.

r_4 = np.random.randint(20,100, size=(4,5))
print(r_4)

[[55 65 67 98 68]
 [65 67 33 28 80]
 [25 41 83 65 74]
 [31 34 92 39 57]]


In [85]:
# Create a variable named r_5 that contains a random set of floats between 0 and 1
# with a size of 4 rows, 5 columns. Print r_5.

r_5 = np.random.rand(4,5)
print(r_5)

[[0.85534778 0.05656036 0.42100789 0.44812092 0.41392519]
 [0.63362849 0.7353471  0.74340044 0.99178786 0.69851109]
 [0.66017409 0.32502813 0.41194613 0.75147255 0.40857779]
 [0.83982731 0.95350242 0.77260167 0.31664264 0.10347036]]


## Generating Random Choices from an Array

In [86]:
# Create a variable named students and assign it a 1-D array containing the names
# of 12 of your classmates.

students = np.array(['Kevin','Edmund','Luis','Hritik','Jeremiah','Natalia','Destiney','Dahlia','Sthefanie','Brandon','Jaquavius','Megatron'])

In [87]:
call_on = np.random.choice(students)
print(call_on)

Brandon


In [88]:
# Create a variable named breakout_groups and use it to choose a random
# sampling from students that is 3 rows, 4 columns in size. Print
# breakout_groups and examine the results – would this be an effective way to
# assign breakout groups? Why or why not? Add a comment to the cell with your
# # 

breakout_groups = np.random.choice(students,size=(3,4))
print(breakout_groups)

# No this would not be an effective way to assign breakout groups because there is the possibility of one person's being called more than once either in the same or a different group 

[['Kevin' 'Jeremiah' 'Natalia' 'Sthefanie']
 ['Brandon' 'Jaquavius' 'Kevin' 'Jaquavius']
 ['Edmund' 'Brandon' 'Natalia' 'Jeremiah']]


In [89]:
# Create a variable named call_on_weighted and use it to choose make five
# random selections from students, but this time assign different probability values
# that will determine how likely each student is to be selected. At least one student
# should have a zero likelihood of being called on, and at least one student should
# have a 30% likelihood of being called on. Distribute other probability values as you
# choose, and in a comment, explain the p values you assigned to each student. Print
# call_on_weighted.

call_on_weighted = np.random.choice(students,size=(4,3),
                                    p=[.05,.05,.1,.05,.05,.05,
                                       .05,.05,.05,.1,.1,.3] )
print(call_on_weighted)

# Kevin has 0% of being selected
# Megatron has 30% of being selected
# Everyone else has either 10% or 5% of being selcted

[['Jeremiah' 'Megatron' 'Jaquavius']
 ['Hritik' 'Megatron' 'Megatron']
 ['Hritik' 'Kevin' 'Megatron']
 ['Megatron' 'Natalia' 'Jaquavius']]


## Generating a Normal Distribution

In [90]:
# Create a variable named bell_curve and assign it a random distribution for
# which the mean (peak of the curve) is 10, the standard deviation is 5, and the size of
# the returned array is 4 rows by 5 columns. Print bell_curve.

bell_curve = np.random.normal(loc=10, scale=5, size=(4,5))
print(bell_curve)

[[ 1.27350818  7.17398356  7.10991546 13.15455624 13.79054604]
 [13.90601188  9.09712882 19.02350319  6.670152    7.09015098]
 [18.11947438  5.30045689 13.0962955   3.28533624  9.92706376]
 [13.1127083   8.12481465 13.58732769 15.95121074 14.12108885]]
