# Exercise 1.B NumPy Random

In [2]:
import numpy as np


## Generating Random Numbers

In [10]:
# Create a variable named r_1 that contains a random set of integers between 1 and
# 20 with a size of 2 elements. Print r_1.

r_1 = np.random.randint(1,20, size=(2))
print(r_1)

[11 17]


In [ ]:
# Create a variable named r_2 that contains a random set of integers between 1 and
# 20 with a size of 1 row, 2 columns. Print r_2.

r_2 = np.random.randint(1,20,size=(1,2))
print(r_2)

[[8 2]]


In [16]:
# Create a variable named r_3 that contains a random set of floats between 0 and 1
# with a size of 2 rows, 1 columns. Print r_3.

r_3 = np.random.randint(1,20, size=(2,1))
print(r_3)

[[ 6]
 [11]]


In [20]:
# Create a variable named r_4 that contains a random set of integers between 20
# and 100 with a size of 4 rows, 5 columns. Print r_4.

r_4 = np.random.randint(20,100, size=(4,5))
print(r_4)

[[30 77 73 61 88]
 [94 41 67 84 99]
 [51 78 23 95 35]
 [39 36 46 59 41]]


In [25]:
# Create a variable named r_5 that contains a random set of floats between 0 and 1
# with a size of 4 rows, 5 columns. Print r_5.

r_5 = np.random.rand(4,5)
print(r_5)

[[0.25082076 0.0541095  0.68703541 0.46566239 0.43802191]
 [0.12382127 0.16493875 0.46289236 0.93399039 0.46382421]
 [0.66893986 0.00544124 0.73925111 0.76764292 0.76239774]
 [0.91380318 0.497958   0.14512088 0.00631284 0.6236333 ]]


## Generating Random Choices from an Array

In [27]:
# Create a variable named students and assign it a 1-D array containing the names
# of 12 of your classmates.

students = np.array(['Kevin','Edmund','Luis','Hritik','Jeremiah','Natalia','Destiney','Dahlia','Sthefanie','Brandon','Jaquavius','Megatron'])

In [30]:
call_on = np.random.choice(students)
print(call_on)

Natalia


In [33]:
# Create a variable named breakout_groups and use it to choose a random
# sampling from students that is 3 rows, 4 columns in size. Print
# breakout_groups and examine the results – would this be an effective way to
# assign breakout groups? Why or why not? Add a comment to the cell with your
# # 

breakout_groups = np.random.choice(students,size=(3,4))
print(breakout_groups)

# No this would not be an effective way to assign breakout groups because there is the possibility of one person's being called more than once either in the same or a different group 

[['Jeremiah' 'Megatron' 'Luis' 'Edmund']
 ['Sthefanie' 'Dahlia' 'Brandon' 'Sthefanie']
 ['Luis' 'Sthefanie' 'Hritik' 'Kevin']]


In [ ]:
# Create a variable named call_on_weighted and use it to choose make five
# random selections from students, but this time assign different probability values
# that will determine how likely each student is to be selected. At least one student
# should have a zero likelihood of being called on, and at least one student should
# have a 30% likelihood of being called on. Distribute other probability values as you
# choose, and in a comment, explain the p values you assigned to each student. Print
# call_on_weighted.

call_on_weighted = np.random.choice(students,size=(4,3),
                                    p=[.05,.05,.1,.05,.05,.05,
                                       .05,.05,.05,.1,.1,.3] )
print(call_on_weighted)

# Kevin has 0% of being selected
# Megatron has 30% of being selected
# Everyone else has either 10% or 5% of being selcted

[['Destiney' 'Luis' 'Brandon']
 ['Brandon' 'Megatron' 'Brandon']
 ['Kevin' 'Brandon' 'Dahlia']
 ['Jaquavius' 'Destiney' 'Sthefanie']]


## Generating a Normal Distribution

In [82]:
# Create a variable named bell_curve and assign it a random distribution for
# which the mean (peak of the curve) is 10, the standard deviation is 5, and the size of
# the returned array is 4 rows by 5 columns. Print bell_curve.

bell_curve = np.random.normal(loc=10, scale=5, size=(4,5))
print(bell_curve)

[[ 9.48000107 12.59474554 16.62064108  9.12706051 11.75252588]
 [12.89646463 12.46767883 10.76054609 -3.86570679  7.73833846]
 [11.09310063 15.32743934  8.27681914 14.73473228 13.26029969]
 [ 5.26451572 -2.04420955  5.99706082  7.89494971 10.96935675]]
