# Exercise 1.C Performing operations on arrays

In [24]:
import numpy as np

## Sample Arrays

In [25]:
# In a code cell, create five variables containing random sample arrays to work with,
# copying over the expressions you used for variables r_1 through r_5 in the
# notebook for Exercise 1.B (NumPy Random).

r_1 = np.random.randint(1,20, size=(2))
r_2 = np.random.randint(1,20,size=(1,2))
r_3 = np.random.rand(1,20)
r_4 = np.random.randint(20,100, size=(4,5))
r_5 = np.random.rand(4,5)

## Permutations

In [26]:
print(r_4)

[[92 60 67 46 59]
 [91 64 86 85 42]
 [80 96 72 99 69]
 [76 43 45 49 59]]


In [27]:
# Use np.random.shuffle to shuffle the values in r_4. Then print r_4 again to view
# the results

np.random.shuffle(r_4)
print(r_4)

[[92 60 67 46 59]
 [91 64 86 85 42]
 [76 43 45 49 59]
 [80 96 72 99 69]]


### Looking at the results of the previous code block, how were the elements of the array shuffled? Add a markdown cell to describe what you find.
The elements of the arrays were being shuffled by only the numbers in their columns. So for column 1 only 35, 95, 94, and 40 were being shuffled and could be in the top spot or any other spot in the column

In [28]:
# Create a new variable named new_shuffle, and assign it the value of a random
# permutation of r_4. Print new_shuffle, and then print r_4 again to compare
# values

new_shuffle = np.random.permutation(r_4)
print(new_shuffle)

[[76 43 45 49 59]
 [91 64 86 85 42]
 [80 96 72 99 69]
 [92 60 67 46 59]]


 ### Add a markdown cell and briefly describe in your own words, when would you use shuffle versus permutation?
 For permutation this time it is rearranging the arrays in order not the elements. You would use shuffle when the data aren't in a group and need to be grouped together so you just shuffly but if they are in a group and that data
 needs to be together like lets say customer an array would have their name, address, blah blah blah. Then you would use permutation to just rearrange the order of customers but keep their information together.

## Mathematical Operations

In [29]:
# Print r_1 and r_2 as starting values, and also print the shape of each using the
# .shape attribute. Then print the result of r_1 plus r_2, using the add function. Also
# print the shape of the result.

print(r_1)
print(r_1.shape)
print(f'\n{r_2}')
print(r_2.shape)

result1 = np.add(r_1,r_2)
print(f'\n{result1}')
print(result1.shape)

[12  6]
(2,)

[[18  4]]
(1, 2)

[[30 10]]
(1, 2)


In [30]:
# Print r_1 and r_3 as starting values, and also print the shape of each using the
# .shape attribute. Then print the result of r_1 plus r_3, using the add function. Also
# print the shape of the result.

print(r_1)
print(r_1.shape)
print(f'\n{r_3}')
print(r_3.shape)

result2 = np.add(r_1,r_3)
print(f'\n{result2}')
print(result2.shape)

[12  6]
(2,)

[[0.03205433 0.89816527 0.7842371  0.56766416 0.9174078  0.15599251
  0.05264913 0.85114377 0.88909025 0.41343881 0.84761618 0.19808433
  0.99631173 0.94728054 0.04230861 0.8309277  0.35150605 0.29469972
  0.00538656 0.39977198]]
(1, 20)


ValueError: operands could not be broadcast together with shapes (2,) (1,20) 

In [ ]:
# Print r_2 and r_4 again as starting values, and also print the shape of each using
# the .shape attribute. Then print the result of r_2 plus r_4, using the add function.
# Also print the shape of the result

print(r_2)
print(f'\n{r_2.shape}')
print(r_4)
print(r_4.shape)

result3 = np.add(r_2,r_4)
print(f'\n{result3}')

[[ 4 19]]

(1, 2)
[[35 53 99 78 57]
 [95 73 28 32 99]
 [40 69 30 30 88]
 [94 86 32 74 22]]
(4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [ ]:
# Create an expression to illustrate what happens when you add r_1 and r_4. What is the error message? How about adding r_2 or r_3 to r_4? 
np.add(r_1,r_4)

# The error message that returns for r_1, r_2, r_3 adding to r_4 is a ValueError as the arrays do not have the same number of columns and rows to be added 

ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [ ]:
# Show what happens if you add np.array([1]) to r_4.
np.add(np.array([1]),r_4)

array([[ 36,  54, 100,  79,  58],
       [ 96,  74,  29,  33, 100],
       [ 41,  70,  31,  31,  89],
       [ 95,  87,  33,  75,  23]])

In [ ]:
# Show what happens if you add np.array([[1]]) to r_4.
np.add(np.array([[1]]),r_4)

array([[ 36,  54, 100,  79,  58],
       [ 96,  74,  29,  33, 100],
       [ 41,  70,  31,  31,  89],
       [ 95,  87,  33,  75,  23]])

In [ ]:
# Show what happens if you add np.array([1,1,1,1,1]) to r_4.
np.add(np.array([1,1,1,1,1]),r_4)

array([[ 36,  54, 100,  79,  58],
       [ 96,  74,  29,  33, 100],
       [ 41,  70,  31,  31,  89],
       [ 95,  87,  33,  75,  23]])

In [ ]:
# What happens if you add np.array([[1],[1]]) to r_4? Add a comment to the cell with the error message this produces.
np.add(np.array([[1],[1]]),r_4)

# It is a ValueError that gets returned saying that you can not broadcast together with the shapes

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

### Add a markdown cell, and in your own words, explain how broadcasting works to combine the values of two arrays. Using the add function, what gets added to what? What determines the shape of the resulting array?
Broadcasting has two rules in order to broadcast two different arrays either their dimensions are equal or one of the dimension is 1 if one of those conditions is met then it will successfully broadcast.
But if one of those is not met it will not broadcast.
Broadcasting stretches the smaller array to match the bigger array and if it only has 1 element it is a clean stretch as it only needs to fill the array with that one element but if there is more than one the stretch becomes messy and there are multiple ways to put multiple elements, it doesn't know what order they should go in. That's why they either need to be the same dimension or is 1 to have a clean stretch


## Rounding

In [ ]:
# Print r_3 to display the values you’ll be working with for the next few cells.
print(r_3)

[[0.51669463 0.81560386 0.57720926 0.41713419 0.51453336 0.55483881
  0.90718773 0.4750887  0.36441769 0.74335075 0.59384845 0.86607714
  0.20957738 0.81819496 0.12488956 0.18485531 0.21451969 0.68492609
  0.22059755 0.79244832]]


In [ ]:
# Round the values in r_3 using trunc.
np.trunc(r_3) # returns the number with the decimal places chopped off

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [ ]:
# Round the values in r_3 using fix.
np.fix(r_3) # rounds to the nearest integer toward zero

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [ ]:
# Round the values in r_3 using floor.
np.floor(r_3) # rounds to the nearest lower integer

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [ ]:
# Round the values in r_3 using ceil.
np.ceil(r_3) # rounds off to the nearest higher integer

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [ ]:
# Round the values in r_3 using round, to 2 decimal places.
np.round(r_3,2) # rounds to the nearest even value

array([[0.52, 0.82, 0.58, 0.42, 0.51, 0.55, 0.91, 0.48, 0.36, 0.74, 0.59,
        0.87, 0.21, 0.82, 0.12, 0.18, 0.21, 0.68, 0.22, 0.79]])

## Cumulative Operations

In [ ]:
# Print r_4 to display the values you’ll be working with for the next few cells.
print(r_4)

[[49 97 82 20 20]
 [63 28 77 79 29]
 [96 31 91 86 36]
 [61 59 86 73 49]]


In [ ]:
# Print the sum of all values in r_4.
print(np.sum(r_4))

1212


In [ ]:
# Print the sum of elements along the 0 axis for r_4.
print(np.sum(r_4,axis=0))

[269 215 336 258 134]


In [ ]:
# Print the sum of elements along the 1 axis for r_4.
print(np.sum(r_4,axis=1))

[268 276 340 328]


In [ ]:
#  Print the cumulative sum (rolling total) of values in r_4.
print(np.cumsum(r_4))

[  49  146  228  248  268  331  359  436  515  544  640  671  762  848
  884  945 1004 1090 1163 1212]


In [ ]:
# Print the cumulative sum (rolling total) of values along the 0 axis for r_4.
print(np.cumsum(r_4,axis=0))

[[ 49  97  82  20  20]
 [112 125 159  99  49]
 [208 156 250 185  85]
 [269 215 336 258 134]]


## Grocery Problem

In [32]:
# Arrays are vegetables,fruits,boxes of snacks, and beverages
bag1 = np.array([2,3,4,0])
bag2 = np.array([4,0,1,2])

print(bag1)
print(bag2)

[2 3 4 0]
[4 0 1 2]


In [ ]:
# Write an expression to calculate the total number of items in each bag, and print the result in the form of a sentence

print(f'The first bag contains {np.sum(bag1)} items, and the second bag contains {np.sum(bag2)} items.')

The first bag contains 9 items, and the second bag contains 7 items.


In [ ]:
#  Write an expression to calculate the total number of items in each category, and print the result in the form of a sentence
total_items = bag1 + bag2

print(f'There are {total_items[0]} vegetables, {total_items[1]} fruits, {total_items[2]} boxes of snacks, and {total_items[3]} beverages in the two grocery bags')

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags


## Teamwork

In [33]:
# Arrays for each member will be ordered as Monday-Friday, monday being index 0 etc etc
ali = np.array([5,4,6,4,2])
ben = np.array([0,5,5,3,4])
carla = np.array([3,6,0,3,4])


In [34]:
# Compile the values reported by Ali, Ben, and Carla into a single array containing all door-knocks for the week, as all_knocks. Print the resulting array.
all_knocks = np.array([ali,ben,carla])
print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [38]:
# Use all_knocks to calculate the total number of doors that each person knocked on for the week, and also the total number of doors that the group collectively knocked on. Print the results.

# Total amount of doors knocks as a group
total_doors_knocks = np.sum(all_knocks)
print(f'The total amount of doors knocked for the week is {total_doors_knocks} doors')

# Total amount doors knocked per person
door_per_person = np.sum(all_knocks, axis=1)
print(f'Ali knocked {door_per_person[0]} doors\nBen knocked {door_per_person[1]}\nCarla knocked {door_per_person[2]} doors')



The total amount of doors knocked for the week is 54 doors
Ali knocked 21 doors
Ben knocked 17
Carla knocked 16 doors


In [48]:
# what is the rolling total of estimated votes that your group was able to turn out, day by day for last week?
daily_knocks = np.sum(all_knocks,axis=0)
# print(daily_knocks)

rolling_total = np.cumsum(daily_knocks) * .5
print(f"Estimated votes for each day:\nMonday's votes: {rolling_total[0]:.0f}\nTuesday's votes: {rolling_total[1]:.0f}\nWednesday's votes: {rolling_total[2]:.0f}\nThursday's votes: {rolling_total[3]:.0f}\nFriday's votes:{rolling_total[4]:.0f}")

Estimated votes for each day:
Monday's votes: 4
Tuesday's votes: 12
Wednesday's votes: 17
Thursday's votes: 22
Friday's votes:27
