# Continuing with NumPy

In [1]:
import numpy as np

In [7]:
start_list = [(1,2,3), ('a','b','c')]

example_a = np.array(start_list)
print(example_a)

[['1' '2' '3']
 ['a' 'b' 'c']]


In [9]:
print(example_a.dtype)

<U21


In [11]:
num_abc = np.array(start_list, dtype="U")

In [12]:
print(num_abc)

[['1' '2' '3']
 ['a' 'b' 'c']]


In [17]:
# use int datatype, converting from float

nums = [1.0,1.1,2.0,2.1]
nums_array = np.array(nums, dtype='i')
print(nums_array)
print(nums_array.dtype)

[1 1 2 2]
int32


# Arrays in loops

In [18]:
arr3d = np.array([
    [[8,7],[6,5]],
    [[4,3],[2,1]],
    [[10,11],[12,13]]
])

In [19]:
for i in arr3d:
    print(i)

[[8 7]
 [6 5]]
[[4 3]
 [2 1]]
[[10 11]
 [12 13]]


In [21]:
for blueberry in arr3d:
    for raspberry in blueberry:
        print(raspberry)

[8 7]
[6 5]
[4 3]
[2 1]
[10 11]
[12 13]


In [23]:
for i in arr3d:
    for x in i:
        for g in x:
            print(g * .75)

6.0
5.25
4.5
3.75
3.0
2.25
1.5
0.75
7.5
8.25
9.0
9.75


In [24]:
for i in arr3d:
    for x in i:
        print(sum(x))

15
11
7
3
21
25


## Concatenating and Stacking Arrays

In [25]:
# array concatenation

arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

arr_c = np.concatenate((arr_a, arr_b)) # concatenation results in the same number of dimensions as the starting arrays
print(arr_c)

[1 2 3 4 5 6]


In [26]:
arr_d = np.stack((arr_a,arr_b)) # stack adds a new dimension to the resulting array
print(arr_d)

[[1 2 3]
 [4 5 6]]


In [27]:
print(arr_d.ndim)
print(arr_d.shape)

2
(2, 3)


In [29]:
combo_d = np.concatenate((arr_d,arr_d), axis = 0) # axis = 0 is the default axis 
print(combo_d)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [30]:
print(combo_d.ndim)
print(combo_d.shape)

2
(4, 3)


In [31]:
combo_d2 = np.concatenate((arr_d,arr_d), axis = 1)
print(combo_d2)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [41]:
# using a practical example

# say I have 2 sets of exam grades, from a original exam date and then a later makeup for some students who needed it

# exam_scores=[.78,.89,.92,82,.99]
# exam_scores_makeup = [.90,.85]

# exam_all = np.concatenate((np.array(exam_scores),np.array(exam_scores_makeup)))
# print(exam_all)

exam_scores = np.array([.78,.89,.92,82,.99])
exam_scores_makeup = np.array([.90,.85])
exam_all = np.concatenate((exam_scores,exam_scores_makeup))

print(exam_all)

[ 0.78  0.89  0.92 82.    0.99  0.9   0.85]


In [43]:
project_scores = np.array([.88,.91,.97,.85,.96,.89,.87])

gradebook = np.stack((exam_all, project_scores))
print(gradebook)

[[ 0.78  0.89  0.92 82.    0.99  0.9   0.85]
 [ 0.88  0.91  0.97  0.85  0.96  0.89  0.87]]


### Working with hstack,vstack,dstack

In [44]:
first_trio = np.array([1, 2, 3])
second_trio = np.array([4, 5, 6])

print(first_trio.ndim)
print(first_trio.shape)

1
(3,)


In [48]:
six_with_hstack = np.hstack((first_trio,second_trio)) # stacks each 1D array "horizontally" end to end 
print(six_with_hstack)

[1 2 3 4 5 6]


In [52]:
six_with_vstack = np.vstack((first_trio,second_trio)) # stacks each 1D array on top of each other "vertically"
print(six_with_vstack)

[[1 2 3]
 [4 5 6]]


In [53]:
six_with_dstack = np.dstack((first_trio,second_trio)) # stacks each 1D array in a new third dimension for depth
print(six_with_dstack)

[[[1 4]
  [2 5]
  [3 6]]]


In [54]:
print(six_with_dstack.ndim)

3


In [55]:
print(six_with_dstack.shape)

(1, 3, 2)


In [61]:
first_quartet = np.array([1, 2, 3,10])
second_quartet = np.array([4, 5, 6,20])

print('using hstack:')
print(np.hstack((first_quartet,second_quartet)))
print(f'\nusing vstack:')
print(np.vstack((first_quartet,second_quartet)))
print(f'\nusing dstack:')
print(np.dstack((first_quartet,second_quartet)))

using hstack:
[ 1  2  3 10  4  5  6 20]

using vstack:
[[ 1  2  3 10]
 [ 4  5  6 20]]

using dstack:
[[[ 1  4]
  [ 2  5]
  [ 3  6]
  [10 20]]]


In [63]:
a = six_with_vstack
b = six_with_vstack
c = six_with_vstack

print(np.hstack((a,b,c))) # hstack will give you a resulting array with the same # of dimensions

[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]]


In [64]:
print(np.dstack((a, b)))
print(np.dstack((a, b)).ndim)
print(np.dstack((a, b)).shape)

[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]
3
(2, 3, 2)


In [67]:
# what do we get if we use hstack with 3D arrays?

print(np.hstack((np.dstack((a,b)),np.dstack((a,b)))))

[[[1 1]
  [2 2]
  [3 3]
  [1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]
  [4 4]
  [5 5]
  [6 6]]]


In [68]:
# what do we get if we use vstack with 3D arrays?

print(np.vstack((np.dstack((a,b)),np.dstack((a,b)))))

[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]

 [[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]


In [69]:
# what do we get if we use dstack with 3D arrays?

print(np.dstack((np.dstack((a,b)),np.dstack((a,b)))))

[[[1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]]

 [[4 4 4 4]
  [5 5 5 5]
  [6 6 6 6]]]
